// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChatRouter(arg1) {
  return window['go']['main']['App']['ChatRouter'](arg1);
}

export function CreateMd(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateMd'](arg1, arg2, arg3, arg4);
}

export function GetAllFile(arg1) {
  return window['go']['main']['App']['GetAllFile'](arg1);
}

export function GetMd(arg1, arg2) {
  return window['go']['main']['App']['GetMd'](arg1, arg2);
}

export function PostOllma(arg1, arg2) {
  return window['go']['main']['App']['PostOllma'](arg1, arg2);
}
