// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ChatRouter(arg1:string):Promise<void>;

export function CreateMd(arg1:string,arg2:string,arg3:number,arg4:string):Promise<boolean>;

export function GetAllFile(arg1:string):Promise<Array<any>>;

export function GetMd(arg1:string,arg2:number):Promise<void>;

export function PostOllma(arg1:string,arg2:string):Promise<main.Message>;
